# build pipeline for Python web app deploying to Azure App Service

trigger:
  - master

variables:
  ConnectedServiceName: "Andrej's Azure Subscription"

jobs:
  - job: hello_world
    displayName: Hello World
    pool:
      vmImage: "ubuntu-latest"
    steps:

  - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.6"
          architecture: "x64"

      - script: |
          # antenv3.6 is the virtual environment name that App Service expects with
          # Python 3.6; use "antenv" for Python 3.7.
          python3.6 -m venv antenv3.6
          source antenv3.6/bin/activate
          pip3.6 install setuptools
          pip3.6 install -r requirements.txt
          pip3.6 install pytest
        # The displayName is shows in the pipeline UI when a build runs
        displayName: "Install Dependencies"
