# build pipeline for Python web app deploying to Azure App Service

trigger:
  - master

variables:
  ConnectedServiceName: "Andrej's Azure Subscription"
  WebAppName: "indypy-demo-2019"

jobs:
  - job: app_service_build
    displayName: App Service Build
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.6"
          architecture: "x64"

      - script: |
          python3.6 -m venv antenv3.6
          source antenv3.6/bin/activate
          pip3.6 install setuptools
          pip3.6 install pytest
          pip3.6 install -r requirements.txt
        displayName: "Install Dependencies"
      - script: |
          source antenv3.6/bin/activate
          cd hello_app
          python3.6 -m pytest
        displayName: "Run tests"
